### ISSUE TITLE
not an issue but suggestion

### ISSUE THREAD

**Issue by danibnnuy** [nyo/scdl#3]
could it be possible to assign a directory to where files will be downloaded so there's no need for downloading tracks one at a time? like how the NotTobi downloader works
also, could it be also possible to add track description in the comment tag in the metadata?

**Comment by danibnnuy** [comment]
i should also add that i'm willing to put in a bit of money for this, i really want a soundcloud downloader that fits all my needs and this is very close to it :3

**Comment by nyo** [comment]
I just added the SoundCloud track description in the comment tag in the metadata (= `COMM` ID3v2.3 tag) based on your suggestion!

For the "default download location" like the NotTobi extension, this would require adding some sort of settings to that add-on, which I'm not willing to do at the moment, I want to keep it very simple. Thanks anyway ✌️
