### ISSUE TITLE
download button not appearing after loading more tracks / opening a single track

### ISSUE THREAD

**Issue by danibnnuy** [nyo/scdl#4]
![imagen](https://github.com/nyo/scdl/assets/109631394/c89da20f-9961-420c-b70a-39bd6da3090b)
![imagen](https://github.com/nyo/scdl/assets/109631394/aabdff25-7e3e-4108-9b33-8ce4d2dd55f7)

**Comment by nyo** [comment]
Hey, thanks for reporting this! I just merged a PR https://github.com/nyo/scdl/pull/6 which should fix it, and released a `v2.1` of the add-on which includes the changes, you should be able to check if these problems persists. 🤓
