### ISSUE TITLE
Download button visible but non-functional

### ISSUE THREAD

**Issue by GravisZro** [nyo/scdl#7]
Thanks for the quick update but despite the `Download` button now being visible, it doesn't actually do anything when clicked.

Here's the page/track where it doesn't work: https://soundcloud.com/vinivicimusic/universe-inside-me

**Comment by nyo** [comment]
Ah yes, good find, I have the problem too, I'll look at it later today.
It works with most of the other tracks right?

**Comment by nyo** [comment]
I found and resolved the issue, just released [v2.2](https://github.com/nyo/scdl/releases/tag/2.2), tell me if it works now

**Comment by GravisZro** [comment]
Just tried it and upon clicking it print the following to the console but no download occurs.

> Some cookies are misusing the recommended “SameSite“ attribute 3
> Cookie “_fbp” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite fbevents.js:24:102380
>
> Cookie “_fbp” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite fbevents.js:24:102380
>
> Cookie “sc_session” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 50-47b07a8b.js:13:299275
>
> [scdl] Trying with 'progressive' transcoding ('audio/mpeg' MIME type)... index.js:237:12
> 

This one song appears to be cursed. :)

**Comment by nyo** [comment]
I just tried with the latest version of the add-on and it worked for me. Sometimes it takes 2-3 sec to open the dialog window,
but when it logs `Trying with 'progressive' transcoding ('audio/mpeg' MIME type)...` with no additional error it means it should work. 🤔

**Comment by GravisZro** [comment]
I checked closer and it was saving it! It wasn't notifying me because of a configuration issue. My bad.
